# =============================================================================
# Ingress для приложения diplom-app
# =============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplom-app
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.dubrovins.ru
      secretName: wildcard-dubrovins-tls
  rules:
    - host: app.dubrovins.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diplom-app
                port:
                  number: 80