controller:
  service:
    type: NodePort
    # Cluster — чтобы health check работал с любого узла,
    # даже если пода ingress там нет
    externalTrafficPolicy: Cluster

    # Фиксируем порты, чтобы NLB в Terraform знал их заранее
    nodePorts:
      http: 30080
      https: 30443

  replicaCount: 2
  # ... остальные настройки без изменений